app/models.py
from datetime import datetime
from flask import current_app, request
from flask_login import UserMixin, AnonymousUserMixin
from . import db, login_manager
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from werkzeug.security import generate_password_hash, check_password_hash
import hashlib

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    __table_args__ = {'extend_existing': True}
    id = db.Column(db.Integer, primary_key=True) # primary keys are required by SQLAlchemy
    email = db.Column(db.String(100), unique=True)
    name = db.Column(db.String(1000))
    password_hash = db.Column(db.String(128))
    avatar_hash = db.Column(db.String(32))
    #achievements = db.relationship('Achievement', backref='author', lazy='dynamic')

    def __repr__(self):
        #return '<User %r>' % self.name
        return self.name

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id}).decode('utf-8')
    
    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def change_email(self, new_email):
        if new_email is None:
            return False
        if self.query.filter_by(email=new_email).first() is not None:
            return False
        self.email = new_email
        db.session.add(self)
        return True

    def gravatar_hash(self):
        return hashlib.md5(self.email.lower().encode('utf-8')).hexdigest()

    def gravatar(self, size=100, default='identicon', rating='g'):
        url = 'https://secure.gravatar.com/avatar'
        hash = self.avatar_hash or self.gravatar_hash()
        return '{url}/{hash}?s={size}&d={default}&r={rating}'.format(
            url=url, hash=hash, size=size, default=default, rating=rating)

class Achievement(db.Model):
    __tablename__ = 'achievement'
    __table_args__ = {'extend_existing': True}
    id = db.Column(db.Integer, primary_key=True)
    achievement = db.Column(db.String(150), nullable=False)
    progress = db.Column(db.String(150), nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    isComplete = db.Column(db.Boolean(), unique=False, default=True)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    author = db.relationship('User', backref='author', foreign_keys=[author_id])

    def __repr__(self):
        return '<Achievement %r>' % self.id   

@login_manager.user_loader
def load_user(user_id):
    # since the user_id is just the primary key of our user table, use it in the query for the user
    return User.query.get(int(user_id))
    # blueprint for auth routes in our app

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, SelectField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
#from ..models import Achievement, User


class AchievementForm(FlaskForm):
    achievement = StringField('Achievement:', validators=[DataRequired()])
    isComplete = BooleanField('Completed?')
    progress = StringField('Progress')
    submit = SubmitField('Add!')

class EditAchievementForm(FlaskForm):
    achievement = StringField('Add a new achievement:', validators=[DataRequired()])
    isComplete = BooleanField('Completed?')
    progress = StringField('Progress')
    submit = SubmitField('Update!')
    cancel = SubmitField('Cancel')

app/__init__.py
from flask import Flask, render_template, Blueprint
from flask_login import LoginManager, login_required, current_user
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from flask_migrate import Migrate
#from .models import User
#from config import config

app = Flask(__name__)
application = app

bootstrap = Bootstrap(app)
moment = Moment(app)
db = SQLAlchemy(app)

app.config['SECRET_KEY'] = 'secret-key-goes-here'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'

login_manager = LoginManager()
login_manager.login_view = 'auth.login'


def create_app():
    
    

    #app.config.from_object(config[config_name])
    #config[config_name].init_app(app)

    #bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, redirect, url_for, abort, flash, request
from flask_login import login_required, current_user
from . import main
from .. import db
from ..models import User, Achievement
from .forms import AchievementForm, EditAchievementForm

#@main.route('/')
#def signup():
#	return render_template('signup.html')

#@main.route('/db', methods = ['GET', 'POST'])
#def index():

	# ----- more db stuff probably goes here ------

#	return render_template('index.html')

@login_required
@main.route('/profile/<username>')
def profile(username):
    allAchievements = Achievement.query.order_by(Achievement.date_created)
    user = User.query.filter_by(name=current_user.name).first_or_404()

    userAchievements = 0
    for i in allAchievements:
        if str(i.author) == current_user.name:
            userAchievements = userAchievements + 1

    completed = 0
    for i in allAchievements:
        if str(i.author) == current_user.name:
            if i.isComplete:
                completed = completed + 1

    inProgress = userAchievements - completed

    return render_template('profile.html', user=user, name=current_user.name, userAchievements=userAchievements, completed=completed, inProgress=inProgress)

# ------ CRUD functions ------
@main.route('/delete/<int:id>')
def delete(id):
    achievement_to_delete = Achievement.query.get_or_404(id)

    try:
        db.session.delete(achievement_to_delete)
        db.session.commit()
        return redirect('/')
        
    except:
        return "There was a problem deleting the achievement"

@login_required
@main.route('/update/<int:id>', methods=['GET', 'POST'])
def update(id):
    achievement = Achievement.query.get_or_404(id)
    form = EditAchievementForm(achievement=achievement)

    if form.validate_on_submit():
        if form.submit.data:
            achievement.achievement = form.achievement.data
            achievement.progress = form.progress.data
            achievement.isComplete = form.isComplete.data
            db.session.add(achievement)
            db.session.commit()
            flash('Achievement updated.')
            return redirect(url_for('.index'))
        else:
            return redirect(url_for('.index'))

    form.achievement.data = achievement.achievement
    form.progress.data = achievement.progress
    form.isComplete.data = achievement.isComplete

    return render_template('update.html', form=form)

@login_required
@main.route('/add', methods=['GET', 'POST'])
def achievements():
    achievement = None
    form = AchievementForm()
    if form.validate_on_submit():
        achievement = Achievement(achievement=form.achievement.data,
                                  progress=form.progress.data,
                                  isComplete=form.isComplete.data,
                                  author=current_user._get_current_object())
        db.session.add(achievement)
        db.session.commit()
        return redirect(url_for('.index'))

    return render_template('new.html', form=form)

@main.route('/', methods=['GET', 'POST'])
def index():
    achievements = Achievement.query.order_by(Achievement.date_created)
    user = User.query.order_by(User.id)

    return render_template("index.html", achievements=achievements, user=user)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Achievement Tracker{% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}"/>
{% endblock styles %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Achievement Tracker</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>

                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('main.profile', username=current_user.name) }}">Profile</a></li>
                {% endif %}    

                {% if not current_user.is_authenticated %}
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    <li><a href="{{ url_for('auth.register') }}">Sign Up</a></li>
                {% endif %}    


                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                {% endif %}                

            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/change_email.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Achievement Tracker {% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}"/>
{% endblock styles %}

{% block page_content %}
<div class="row">
	<div class="col md-12">
		<div class="jumbotron p-3">
			<div class="container column is-4 is-offset-4">
				<h2>Change Email</h2>

					{{ wtf.quick_form(form) }}

			</div>
		</div>
	</div>
</div>
{% endblock %}

app/templates/change_password.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Achievement Tracker {% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}"/>
{% endblock styles %}

{% block page_content %}
<div class="row">
	<div class="col md-12">
		<div class="jumbotron p-3">
			<div class="container column is-4 is-offset-4">
				<h2>Change Password</h2>

					{{ wtf.quick_form(form) }}

			</div>
		</div>
	</div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Achievement Tracker {% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}"/>
{% endblock styles %}

{% block page_content %}

	{% if current_user.is_authenticated %}
		<div class = "text-right">
			<a class = "btn btn-primary" href="{{ url_for('main.achievements') }}">Add Achievement</a>
		</div>
	{% endif %}

	<div class="row">
		<div class="col md-12">
			<div class="jumbotron p-3">

				<h2>In <b>Progress</b></h2>
	
					<table class="table table-hover table-dark">

						<tr>
							<th>Name</th>
							<th>Achievement</th>
							<th>Progress</th>
							<th>Completed?</th>
							
							{% if current_user.is_authenticated %}
								<th>Options</th>
							{% endif %}						
						</tr>

						{% for achievement in achievements %}

							{% if not achievement.isComplete %}

								{% if achievement.author|string() == current_user.name|string() %}

									<tr>
										<td><img class="img-rounded" src="{{ achievement.author.gravatar(size=36) }}">  {{ achievement.author }}</td>
										<td>{{ achievement.achievement }}</td>
										<td>{{ achievement.progress }}</td>

										{% if achievement.isComplete %}
											<td>Yes</td>
										{% else %}
											<td>No</td>
										{% endif %}

										{% if current_user.is_authenticated %}
											<td><a class = "btn btn-warning btn-xs" href="/update/{{achievement.id}}">Update</a> <a class = "btn btn-danger btn-xs" onclick="return confirm('Are you sure you want to delete?')" href="/delete/{{achievement.id}}">Delete</a></td>
										{% endif %}
									</tr>

								{% endif %}

							{% endif %}

						{% endfor %}

					</table>	

				<br>	<br>	<br>	<br>

				<h2>Completed <b>Achievements</b></h2>

					<table class="table table-hover table-dark">

						<tr>
							<th>User</th>
							<th>Achievement</th>
							<th>Progress</th>
							<th>Completed?</th>

							{% if current_user.is_authenticated %}
								<th>Options</th>
							{% endif %}

						</tr>

						{% for achievement in achievements %}

							{% if achievement.isComplete %}

								{% if achievement.author|string() == current_user.name|string() %}
				
									<tr>
										<td><img class="img-rounded" src="{{ achievement.author.gravatar(size=36) }}">  {{ achievement.author }}</td>
										<td>{{ achievement.achievement }}</td>
										<td>{{ achievement.progress }}</td>

										{% if achievement.isComplete %}
											<td>Yes</td>
										{% else %}
											<td>No</td>
										{% endif %}

										{% if current_user.is_authenticated %}
											<td><a class = "btn btn-warning btn-xs" href="/update/{{achievement.id}}">Update</a> <a class = "btn btn-danger btn-xs" onclick="return confirm('Are you sure you want to delete?')" href="/delete/{{achievement.id}}">Delete</a></td>
										{% endif %}

									</tr>

								{% endif %}

							{% endif %}

						{% endfor %}

					</table>

			</div>
		</div>
	</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Achievement Tracker {% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}"/>
{% endblock styles %}

{% block page_content %}
<div class="row">
	<div class="col md-12">
		<div class="jumbotron p-3">
			<div class="container column is-4 is-offset-4">
				<h2>Login</h2>

					{{ wtf.quick_form(form) }}

			</div>
		</div>
	</div>
</div>
{% endblock %}

app/templates/new.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Achievement Tracker {% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}"/>
{% endblock styles %}

{% block page_content %}
<div class="row">
	<div class="col md-12">
		<div class="jumbotron p-3">
			<div class="container column is-4 is-offset-4">
				<h2>Add a new Achievement</h2>

					{{ wtf.quick_form(form) }}
					
			</div>
		</div>
	</div>
</div>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Achievement Tracker{% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}"/>
{% endblock styles %}

{% block page_content %}
<div class="row">

	<div class="col md-12">

		<img class="img-rounded profile-thumbnail" src="{{ user.gravatar(size=256) }}">

		<div class="profile-header">

			<h1>Welcome, {{ current_user.name }}!</h1>
						
				<hr>
				
				<p>In Progress Achievements: {{ inProgress }} </p>
				<p>Completed Achievements: {{ completed }}</p>
				<p>Total Achievements: {{ userAchievements }}</p>

				<br> <br>
					
				<a class="btn btn-primary" href="{{ url_for('auth.change_password') }}">Change password</a>
				<a class="btn btn-primary" href="{{ url_for('auth.change_email') }}">Change email</a>

		</div>

	</div>
	
</div>

{% endblock %}

app/templates/signup.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Achievement Tracker {% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}"/>
{% endblock styles %}

{% block page_content %}
<div class="row">
	<div class="col md-12">
		<div class="jumbotron p-3">
			<div class="container column is-4 is-offset-4">
				<h2>Signup</h2>

					{{ wtf.quick_form(form) }}

			</div>
		</div>
	</div>
</div>
{% endblock %}

app/templates/update.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Achievement Tracker{% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}"/>
{% endblock styles %}

{% block page_content %}
    <h1>Edit Achievement</h1>

    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
        
{% endblock %}